name: Auto-Update Dependencies

on:
  schedule:
    - cron: '0 1 * * 1'  # Every Monday at 1 AM
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      
      - name: Update npm dependencies
        run: |
          if [ -f package.json ]; then
            npx npm-check-updates -u
            npm install
          fi
      
      - name: Run tests after update
        run: npm test --if-present || true
      
      - name: Create PR for updates
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          if ! git diff --staged --quiet; then
            git commit -m "🤖 Auto-update: dependencies"
            git push -u origin HEAD:auto-update-deps-$(date +%Y%m%d) || true
          fi
